name: Test Schedule
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World at $(date)"