name: Schedule POST Request
on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-telegram-bot-api-secret-token: ${{ secrets.TELEGRAM_SECRET_TOKEN }}" \
            -d '{"broadcoast_triggers": ["updates", "system"]}' \
            https://gekkobot-delta.vercel.app/api/telegram/xbot