name: Schedule YBOT Broadcoast Request
on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-telegram-bot-api-secret-token: ${{ secrets.TELEGRAM_SECRET_TOKEN }}" \
            -d '{"broadcoast_triggers": ["balance", "system"]}' \
            https://gekkobot-delta.vercel.app/api/telegram/ybot